if(NOT _VCPKG_WINDOWS_CLANGCL_TOOLCHAIN)
  set(_VCPKG_WINDOWS_CLANGCL_TOOLCHAIN 1)

  set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>$<$<STREQUAL:${VCPKG_CRT_LINKAGE},dynamic>:DLL>" CACHE STRING "")
  set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "")

  if(POLICY CMP0056)
    cmake_policy(SET CMP0056 NEW)
  endif()
  if(POLICY CMP0066)
    cmake_policy(SET CMP0066 NEW)
  endif()
  if(POLICY CMP0067)
    cmake_policy(SET CMP0067 NEW)
  endif()
  if(POLICY CMP0137)
    cmake_policy(SET CMP0137 NEW)
  endif()
  list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    VCPKG_CRT_LINKAGE
    VCPKG_TARGET_ARCHITECTURE
    VCPKG_SET_CHARSET_FLAG
    VCPKG_C_FLAGS
    VCPKG_CXX_FLAGS
    VCPKG_C_FLAGS_DEBUG
    VCPKG_CXX_FLAGS_DEBUG
    VCPKG_C_FLAGS_RELEASE
    VCPKG_CXX_FLAGS_RELEASE
    VCPKG_LINKER_FLAGS
    VCPKG_LINKER_FLAGS_RELEASE
    VCPKG_LINKER_FLAGS_DEBUG
    VCPKG_PLATFORM_TOOLSET
    VCPKG_USE_LTO
  )

  set(CMAKE_SYSTEM_NAME Windows CACHE STRING "")

  if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x86")
    set(CMAKE_SYSTEM_PROCESSOR x86 CACHE STRING "")
  elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
    set(CMAKE_SYSTEM_PROCESSOR AMD64 CACHE STRING "")
  elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm")
    set(CMAKE_SYSTEM_PROCESSOR ARM CACHE STRING "")
  elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64")
    set(CMAKE_SYSTEM_PROCESSOR ARM64 CACHE STRING "")
  endif()

  if(DEFINED VCPKG_CMAKE_SYSTEM_VERSION)
    set(CMAKE_SYSTEM_VERSION "${VCPKG_CMAKE_SYSTEM_VERSION}" CACHE STRING "" FORCE)
  endif()

  if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    if(CMAKE_SYSTEM_PROCESSOR STREQUAL CMAKE_HOST_SYSTEM_PROCESSOR)
      set(CMAKE_CROSSCOMPILING OFF CACHE STRING "")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86")
      set(CMAKE_CROSSCOMPILING OFF CACHE STRING "")
    elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "ARM64")
      set(CMAKE_CROSSCOMPILING OFF CACHE STRING "")
    endif()

    if(NOT DEFINED CMAKE_SYSTEM_VERSION)
      set(CMAKE_SYSTEM_VERSION "${CMAKE_HOST_SYSTEM_VERSION}" CACHE STRING "")
    endif()
  endif()

  if(VCPKG_CRT_LINKAGE STREQUAL "dynamic")
    set(VCPKG_CRT_LINK_FLAG_PREFIX "/MD")
  elseif(VCPKG_CRT_LINKAGE STREQUAL "static")
    set(VCPKG_CRT_LINK_FLAG_PREFIX "/MT")
  else()
    message(FATAL_ERROR "Invalid setting for VCPKG_CRT_LINKAGE: \"${VCPKG_CRT_LINKAGE}\". It must be \"static\" or \"dynamic\"")
  endif()

  set(VCPKG_CHARSET_FLAG "/utf-8")
  if(NOT VCPKG_SET_CHARSET_FLAG OR VCPKG_PLATFORM_TOOLSET MATCHES "v120")
    set(VCPKG_CHARSET_FLAG "")
  endif()

  find_program(VCPKG_CLANGCL_EXECUTABLE NAMES clang-cl clang-cl.exe PATHS ENV LLVMInstallDir PATH_SUFFIXES bin NO_DEFAULT_PATH)
  if(NOT VCPKG_CLANGCL_EXECUTABLE)
    find_program(VCPKG_CLANGCL_EXECUTABLE NAMES clang-cl clang-cl.exe)
  endif()
  if(NOT VCPKG_CLANGCL_EXECUTABLE)
    message(FATAL_ERROR "clang-cl was not found")
  endif()

  get_filename_component(VCPKG_LLVM_BIN_DIR "${VCPKG_CLANGCL_EXECUTABLE}" DIRECTORY)
  list(INSERT CMAKE_PROGRAM_PATH 0 "${VCPKG_LLVM_BIN_DIR}")

  set(CMAKE_C_COMPILER "${VCPKG_CLANGCL_EXECUTABLE}" CACHE STRING "")
  set(CMAKE_CXX_COMPILER "${VCPKG_CLANGCL_EXECUTABLE}" CACHE STRING "")

  find_program(VCPKG_LLVM_LIB_EXECUTABLE NAMES llvm-lib llvm-lib.exe PATHS "${VCPKG_LLVM_BIN_DIR}" NO_DEFAULT_PATH)
  find_program(VCPKG_LLD_LINK_EXECUTABLE NAMES lld-link lld-link.exe PATHS "${VCPKG_LLVM_BIN_DIR}" NO_DEFAULT_PATH)
  if(VCPKG_LLVM_LIB_EXECUTABLE)
    set(CMAKE_AR "${VCPKG_LLVM_LIB_EXECUTABLE}" CACHE STRING "")
  endif()
  if(VCPKG_LLD_LINK_EXECUTABLE)
    set(CMAKE_LINKER "${VCPKG_LLD_LINK_EXECUTABLE}" CACHE STRING "")
  endif()

  set(VCPKG_CLANGCL_ARCH_FLAGS "")
  if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64" OR VCPKG_TARGET_ARCHITECTURE STREQUAL "x86")
    string(APPEND VCPKG_CLANGCL_ARCH_FLAGS " /clang:-mcrc32 /clang:-msse4.2 /clang:-maes /clang:-mpclmul")
  endif()

  if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x86")
    string(APPEND VCPKG_CLANGCL_ARCH_FLAGS " /clang:-m32 /clang:--target=i686-pc-windows-msvc")
  endif()

  if(VCPKG_USE_LTO)
    if(NOT VCPKG_LLVM_LIB_EXECUTABLE OR NOT VCPKG_LLD_LINK_EXECUTABLE)
      message(FATAL_ERROR "VCPKG_USE_LTO requires llvm-lib and lld-link in the selected LLVM toolchain")
    endif()
    string(APPEND VCPKG_C_FLAGS_RELEASE " -flto")
    string(APPEND VCPKG_CXX_FLAGS_RELEASE " -flto -fwhole-program-vtables")
  endif()

  set(VCPKG_MP_BUILD_FLAG "")
  if(NOT CMAKE_CXX_COMPILER MATCHES "clang-cl(\\.exe)?$")
    set(VCPKG_MP_BUILD_FLAG "/MP ")
  endif()

  set(CMAKE_CXX_FLAGS " /nologo /DWIN32 /D_WINDOWS ${VCPKG_CHARSET_FLAG} /GR /EHsc ${VCPKG_MP_BUILD_FLAG}${VCPKG_CLANGCL_ARCH_FLAGS}${VCPKG_CXX_FLAGS}" CACHE STRING "")
  set(CMAKE_C_FLAGS " /nologo /DWIN32 /D_WINDOWS ${VCPKG_CHARSET_FLAG} ${VCPKG_MP_BUILD_FLAG}${VCPKG_CLANGCL_ARCH_FLAGS}${VCPKG_C_FLAGS}" CACHE STRING "")

  if(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64ec")
    string(APPEND CMAKE_CXX_FLAGS " /arm64EC /D_AMD64_ /DAMD64 /D_ARM64EC_ /DARM64EC")
    string(APPEND CMAKE_C_FLAGS " /arm64EC /D_AMD64_ /DAMD64 /D_ARM64EC_ /DARM64EC")
  endif()
  set(CMAKE_RC_FLAGS "-c65001 /DWIN32" CACHE STRING "")

  set(CMAKE_CXX_FLAGS_DEBUG "${VCPKG_CRT_LINK_FLAG_PREFIX}d /Z7 /Ob0 /Od /RTC1 ${VCPKG_CXX_FLAGS_DEBUG}" CACHE STRING "")
  set(CMAKE_C_FLAGS_DEBUG "${VCPKG_CRT_LINK_FLAG_PREFIX}d /Z7 /Ob0 /Od /RTC1 ${VCPKG_C_FLAGS_DEBUG}" CACHE STRING "")
  set(CMAKE_CXX_FLAGS_RELEASE "${VCPKG_CRT_LINK_FLAG_PREFIX} /O2 /Oi /Gy /DNDEBUG /Z7 ${VCPKG_CXX_FLAGS_RELEASE}" CACHE STRING "")
  set(CMAKE_C_FLAGS_RELEASE "${VCPKG_CRT_LINK_FLAG_PREFIX} /O2 /Oi /Gy /DNDEBUG /Z7 ${VCPKG_C_FLAGS_RELEASE}" CACHE STRING "")

  string(APPEND CMAKE_STATIC_LINKER_FLAGS_RELEASE_INIT " /nologo ")
  set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "/nologo /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")
  set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "/nologo /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")
  set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/nologo /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")

  string(APPEND CMAKE_STATIC_LINKER_FLAGS_DEBUG_INIT " /nologo ")
  string(APPEND CMAKE_MODULE_LINKER_FLAGS_DEBUG_INIT " /nologo ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_DEBUG} ")
  string(APPEND CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT " /nologo ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_DEBUG} ")
  string(APPEND CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT " /nologo ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_DEBUG} ")

  unset(VCPKG_CHARSET_FLAG)
  unset(VCPKG_CLANGCL_ARCH_FLAGS)
  unset(VCPKG_MP_BUILD_FLAG)
  unset(VCPKG_CRT_LINK_FLAG_PREFIX)
  unset(VCPKG_CLANGCL_EXECUTABLE)
  unset(VCPKG_LLVM_BIN_DIR)
  unset(VCPKG_LLVM_LIB_EXECUTABLE)
  unset(VCPKG_LLD_LINK_EXECUTABLE)
endif()
